name: Available contexts

env:
  WF_ENV: 'workflow env var'

on:
  push:

jobs:
  # https://docs.github.com/en/actions/learn-github-actions/contexts
  contexts:
    runs-on: ubuntu-latest
    env:
      J_ENV: 'job env var'
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      -
        name: github
        run: echo "${{ toJSON(github) }}"
      -
        name: env
        run: echo "${{ toJSON(env) }}"
        env:
          S_ENV: 'step env var'
      -
        name: job
        run: echo "${{ toJSON(job) }}"
      -
        name: steps
        id: step1
        run: echo "${{ toJSON(steps) }} ::set-output name=test::hello"
      -
        name: runner
        run: echo "${{ toJSON(runner) }}"
      -
        name: secrets
        run: echo "${{ toJSON(secrets) }}"
      -
        name: strategy
        run: echo "${{ toJSON(strategy) }}"
      -
        name: needs
        run: echo "${{ toJSON(needs) }}"
      -
        name: inputs
        run: echo "${{ toJSON(inputs) }}"
