name: Build an artifact and utilize a custom action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        run: docker build -t build-time-capturer src
      -
        run: docker run build-time-capturer
      -
        run: docker save build-time-capturer > build-time-capturer.tar
      -
        run: ls -l
      -
        run: gzip build-time-capturer.tar
      -
        run: ls -l
      -
        uses: actions/upload-artifact@v2
        with:
          name: build-time-capturer.tar.gz
          path: build-time-capturer.tar.gz
        # run custom action passing in artifact id
