name: Data sharing

on:
  push:
  workflow_dispatch:

jobs:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
  between-steps-via-output:
    runs-on: ubuntu-latest
    steps:
      -
        id: vars
        run: echo ::set-output name=EPOCH::$(date +%s)
      -
        run: sleep 2
      -
        run: echo "The previous step ran at ${{ steps.vars.outputs.EPOCH }};  it is now $(date +%s)"
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idoutputs
  between-jobs-generate-output:
    runs-on: ubuntu-latest

    outputs:
      EPOCH: ${{ steps.vars.outputs.EPOCH_IN_STEP }}

    steps:
      -
        id: vars
        run: echo ::set-output name=EPOCH_IN_STEP::$(date +%s)
      -
        run: echo "The previous step ran at ${{ steps.vars.outputs.EPOCH_IN_STEP }};  it is now $(date +%s)"

  between-jobs-consume-output:
    runs-on: ubuntu-latest
    needs: between-jobs-generate-output
    steps:
      -
        run: echo "The previous job ran at ${{ needs.between-jobs-generate-output.outputs.EPOCH }};  it is now $(date +%s)"

  # TODO: artifacts between jobs (https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs)
  # TODO: ref to docs
  # TODO: use `needs` between jobs
