name: Manual run Demo
on:
  workflow_dispatch:
    inputs:
      # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_id
      whom:
        description: Whom to greet
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.whom }}"
