name: Running a workflow manually

on:
  workflow_dispatch:
    inputs:
      # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_id
      whom:
        description: Whom to greet
        required: true
      emote:
        description: Emotion toward meeting "whom"
        default: 'nice'
        required: true
      tense:
        description: Tense of greeting
        type: choice
        options:
          - 'is'
          - 'was'
      truth:
        description: I mean it
        type: boolean
        default: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      -
        run: echo "Hello ${{ github.event.inputs.whom }}, it ${{ github.event.inputs.tense }} ${{ github.event.inputs.emote }} to meet you."
      -
        run: echo "Truthfully? [${{ github.event.inputs.truth }}]"
