name: Manual run Demo
on:
  workflow_dispatch:
    inputs:
      whom:
        description: Whom to greet
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.whom }}"
