name: Windows runner

on:
  push:
    branches: 'windows-access-db'

jobs:
  info:
    runs-on: windows-latest

    steps:
      -
        uses: actions/checkout@v4
      -
        name: Current dir
        run: dir
      -
        name: python version
        run: python -V
