name: Windows runner

on:
  push:
    branches: 'windows-access-db'

jobs:
  init:
    runs-on: windows-latest

    steps:
      -
        uses: actions/checkout@v4
      -
        name: Current dir
        run: dir
      -
        # https://docs.python.org/3/using/cmdline.html#generic-options
        name: python version
        run: python -V
      -
        name: execute script
        run: python src/msaccess.py
