name: Windows runner

on:
  push:
    branches: 'windows-access-db'

jobs:
  check :
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest

    steps:
      -
        uses: actions/checkout@v4
      -
        name: Current dir
        run: dir
      -
        name: Program Files dir
        run: dir "C:\Program Files"
      -
        # https://docs.python.org/3/using/cmdline.html#generic-options
        name: python version
        run: python -V
      -
        name: install pyodbc
        run: pip install pyodbc
      -
        run: "Get-OdbcDriver | Where-Object { $_.Name -like '*Access*' }"
      -
        name: execute script
        run: python src/msaccess.py
